networks:
    local:
        driver: bridge
services:
  # Application Service
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    image: footballer-profile-app
    container_name: footballer-profile-app
#    command: php artisan migrate
    restart: unless-stopped
    volumes:
      - .:/var/www/html
#      - ./docker/app/php.ini:/usr/local/etc/php/conf.d/local.ini
    environment:
      - "PHP_MEMORY_LIMIT=512M"
    depends_on:
      - postgres
      - redis
    ports:
        - "5173:5173"
    networks:
        - local


  # Web Server (Nginx)
  nginx:
    image: nginx:1.25-alpine
    container_name: footballer-profile-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
        - local


  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: footballer-profile-postgres
    restart: unless-stopped
    environment:
        POSTGRES_USER: username
        POSTGRES_PASSWORD: password
        POSTGRES_DB: futemon
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
        - local


  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: footballer-profile-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
        - local


#  # Queue Worker
  queue-worker:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    image: footballer-profile-app
    container_name: footballer-profile-queue
    restart: unless-stopped
    command: php artisan queue:work --tries=3 --timeout=90
    volumes:
      - .:/var/www/html
    depends_on:
      - app
      - postgres
      - redis
    networks:
        - local


#
#  # Scheduler
  scheduler:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    image: footballer-profile-app
    container_name: footballer-profile-scheduler
    restart: unless-stopped
    command: php artisan schedule:work
    volumes:
      - .:/var/www/html
    depends_on:
      - app
      - postgres
      - redis
    networks:
        - local

volumes:
  postgres_data:
  redis_data:
